### ISSUE TITLE
would you can the glyphicon icon's prefix

### ISSUE THREAD

**Issue by ilovezy** [idleberg/Icon-Fonts-Sublime-Text#4]
I use bootstrap, maybe change the glyphicon to gly or something shotter please, this prefix is too long

**Comment by idleberg** [comment]
You don't have to type the full prefix. If you prefer `gly`, you can use that. Chances are that in many cases `g` will be enough.

Give it a try:
`glyph-checks`, `g-checks` and `gchk` all complete to `glyphicon glyphicon-check`

**Comment by ilovezy** [comment]
yean,that finished, just one problem like bootstrap3-snippet
I need to tap < first to trigger the icon , it lead to this, there is one more < before
![qq 20150803143810](https://cloud.githubusercontent.com/assets/8774988/9032070/5611a012-39ed-11e5-811d-a48380c91cbd.png)

I set this to fix bootstrap3-snippet problem
![qq 20150803143907](https://cloud.githubusercontent.com/assets/8774988/9032079/6be5e5ba-39ed-11e5-971c-691d5585f2cc.png)

can I fix this problem by doing like this, how to set?

**Comment by idleberg** [comment]
You're not supposed to press <kbd>&lt;</kbd> before using the completion. Standard HTML-completions and Bootstrap 3 snippets follow that behaviour as well.

I'm not familiar with the `auto_complete_triggers` setting, I'm using the following myself:

    "auto_complete_selector": "source, meta.tag, text"

**Comment by ilovezy** [comment]
prefect,you setting fixed my final question on sublime, thanks so much
